name: Test

on:
  pull_request:
  push:
    branches:
      - main

jobs:
  php-tests:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        php-version:
          - '7.4'
          - '8.1'

    steps:
      - name: Checkout
        uses: actions/checkout@v6

      - name: Set up PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: ${{ matrix.php-version }}
          coverage: none

      - name: Validate Composer files
        run: composer validate --no-check-lock

      - name: Install Composer dependencies
        run: composer update --no-interaction --prefer-dist --no-audit

      - name: Run PHPUnit
        run: composer test

      - name: Run PHPCS
        run: composer lint
